### ISSUE TITLE
checks by partialsmiles perhaps not in sync with warnings by OpenBabel

### ISSUE THREAD

**Issue by nbehrnd** [baoilleach/partialsmiles#5]
Passing the same SMILES string to OpenBabel and to partialsmiles suggests the later does not cover (yet) all the criteria of the former.

Dealing with the SMILES string about a diene, OpenBabel issues a warning:

```bash
$ obabel -:"CC(O/C(\CCC[C@H]([C@H](C(CC=C)=C)OC(O)=C)O)=C(\COC)/OCO)=O" -ocan
==============================
*** Open Babel Warning  in CreateCisTrans
  Error in cis/trans stereochemistry specified for the double bond

COCC(=C(OC(=O)C)CCC[C@H]([C@H](C(=C)CC=C)OC(=C)O)O)OCO	
1 molecule converted
```
while partialsmiles' does not/does not yet:

```bash
$ python3 validate.py "CC(O/C(\CCC[C@H]([C@H](C(CC=C)=C)OC(O)=C)O)=C(\COC)/OCO)=O"
Input: CC(O/C(\CCC[C@H]([C@H](C(CC=C)=C)OC(O)=C)O)=C(\COC)/OCO)=O

1. Parse as full SMILES:

OK

2. Parse as partial SMILES:

OK

3. Parse substrings as partial SMILES:

OK
```
Observation with OpenBabel 3.1.1 (3.1.1+dfsg-6+1b) in Linux Debian 12/bookworm (branch testing) and partialsmiles (version 1.0).

**Comment by baoilleach** [comment]
This is covered in the docs: https://baoilleach.github.io/partialsmiles/errors.html

"Note that detection of stereochemistry-related errors is not currently supported." Stereo is usually not present in the SMILES strings created by generative models. Would be nice to support it, but I have no plans to do this at the moment.
